// source: src/grpc/car_model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.jpan.autodealer.grpc.CarModelCreateRequest', null, global);
goog.exportSymbol('proto.com.jpan.autodealer.grpc.CarModelFetchRequest', null, global);
goog.exportSymbol('proto.com.jpan.autodealer.grpc.CarModelSearchRequest', null, global);
goog.exportSymbol('proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest', null, global);
goog.exportSymbol('proto.com.jpan.autodealer.grpc.CarModelVO', null, global);
goog.exportSymbol('proto.com.jpan.autodealer.grpc.FuelType', null, global);
goog.exportSymbol('proto.com.jpan.autodealer.grpc.PageCarModelResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jpan.autodealer.grpc.CarModelVO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.jpan.autodealer.grpc.CarModelVO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.jpan.autodealer.grpc.CarModelVO.displayName = 'proto.com.jpan.autodealer.grpc.CarModelVO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.jpan.autodealer.grpc.CarModelCreateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.jpan.autodealer.grpc.CarModelCreateRequest.displayName = 'proto.com.jpan.autodealer.grpc.CarModelCreateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.jpan.autodealer.grpc.CarModelFetchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.jpan.autodealer.grpc.CarModelFetchRequest.displayName = 'proto.com.jpan.autodealer.grpc.CarModelFetchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.jpan.autodealer.grpc.CarModelSearchRequest.repeatedFields_, null);
};
goog.inherits(proto.com.jpan.autodealer.grpc.CarModelSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.jpan.autodealer.grpc.CarModelSearchRequest.displayName = 'proto.com.jpan.autodealer.grpc.CarModelSearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.displayName = 'proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.jpan.autodealer.grpc.PageCarModelResponse.repeatedFields_, null);
};
goog.inherits(proto.com.jpan.autodealer.grpc.PageCarModelResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.jpan.autodealer.grpc.PageCarModelResponse.displayName = 'proto.com.jpan.autodealer.grpc.PageCarModelResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jpan.autodealer.grpc.CarModelVO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jpan.autodealer.grpc.CarModelVO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelVO.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 3, 0),
    version: jspb.Message.getFieldWithDefault(msg, 4, ""),
    year: jspb.Message.getFieldWithDefault(msg, 5, 0),
    price: jspb.Message.getFieldWithDefault(msg, 6, ""),
    fueltype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    fuelconsumptionkmperl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    annualmaintenancecost: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jpan.autodealer.grpc.CarModelVO;
  return proto.com.jpan.autodealer.grpc.CarModelVO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelVO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBrand(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setYear(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrice(value);
      break;
    case 7:
      var value = /** @type {!proto.com.jpan.autodealer.grpc.FuelType} */ (reader.readEnum());
      msg.setFueltype(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFuelconsumptionkmperl(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnualmaintenancecost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jpan.autodealer.grpc.CarModelVO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelVO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelVO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBrand();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getYear();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPrice();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getFueltype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getFuelconsumptionkmperl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getAnnualmaintenancecost();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 brand = 3;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getBrand = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setBrand = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string version = 4;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 year = 5;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getYear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setYear = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string price = 6;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional FuelType fuelType = 7;
 * @return {!proto.com.jpan.autodealer.grpc.FuelType}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getFueltype = function() {
  return /** @type {!proto.com.jpan.autodealer.grpc.FuelType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.com.jpan.autodealer.grpc.FuelType} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setFueltype = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string fuelConsumptionKmPerL = 8;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getFuelconsumptionkmperl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setFuelconsumptionkmperl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string annualMaintenanceCost = 9;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.getAnnualmaintenancecost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelVO.prototype.setAnnualmaintenancecost = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jpan.autodealer.grpc.CarModelCreateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 2, 0),
    version: jspb.Message.getFieldWithDefault(msg, 3, ""),
    year: jspb.Message.getFieldWithDefault(msg, 4, 0),
    price: jspb.Message.getFieldWithDefault(msg, 5, ""),
    fueltype: jspb.Message.getFieldWithDefault(msg, 6, 0),
    fuelconsumptionkmperl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    annualmaintenancecost: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jpan.autodealer.grpc.CarModelCreateRequest;
  return proto.com.jpan.autodealer.grpc.CarModelCreateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBrand(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setYear(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrice(value);
      break;
    case 6:
      var value = /** @type {!proto.com.jpan.autodealer.grpc.FuelType} */ (reader.readEnum());
      msg.setFueltype(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setFuelconsumptionkmperl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnualmaintenancecost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jpan.autodealer.grpc.CarModelCreateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBrand();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getYear();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getPrice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFueltype();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getFuelconsumptionkmperl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getAnnualmaintenancecost();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 brand = 2;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getBrand = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setBrand = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string version = 3;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 year = 4;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getYear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setYear = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string price = 5;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional FuelType fuelType = 6;
 * @return {!proto.com.jpan.autodealer.grpc.FuelType}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getFueltype = function() {
  return /** @type {!proto.com.jpan.autodealer.grpc.FuelType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.com.jpan.autodealer.grpc.FuelType} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setFueltype = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional string fuelConsumptionKmPerL = 7;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getFuelconsumptionkmperl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setFuelconsumptionkmperl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string annualMaintenanceCost = 8;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.getAnnualmaintenancecost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelCreateRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelCreateRequest.prototype.setAnnualmaintenancecost = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jpan.autodealer.grpc.CarModelFetchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jpan.autodealer.grpc.CarModelFetchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelFetchRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jpan.autodealer.grpc.CarModelFetchRequest;
  return proto.com.jpan.autodealer.grpc.CarModelFetchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelFetchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelFetchRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jpan.autodealer.grpc.CarModelFetchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelFetchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelFetchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelFetchRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jpan.autodealer.grpc.CarModelSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    minyear: jspb.Message.getFieldWithDefault(msg, 1, 0),
    maxyear: jspb.Message.getFieldWithDefault(msg, 2, 0),
    makeList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    page: jspb.Message.getFieldWithDefault(msg, 4, 0),
    size: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jpan.autodealer.grpc.CarModelSearchRequest;
  return proto.com.jpan.autodealer.grpc.CarModelSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinyear(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxyear(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setMakeList(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jpan.autodealer.grpc.CarModelSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMinyear();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMaxyear();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMakeList();
  if (f.length > 0) {
    writer.writePackedInt64(
      3,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional int32 minYear = 1;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.getMinyear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.setMinyear = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 maxYear = 2;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.getMaxyear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.setMaxyear = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated int64 make = 3;
 * @return {!Array<number>}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.getMakeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.setMakeList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.addMake = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.clearMakeList = function() {
  return this.setMakeList([]);
};


/**
 * optional int32 page = 4;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 size = 5;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSearchRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSearchRequest.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    monthlytraveldistance: jspb.Message.getFieldWithDefault(msg, 1, ""),
    periodinyears: jspb.Message.getFieldWithDefault(msg, 2, 0),
    fuelpriceineurperl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    page: jspb.Message.getFieldWithDefault(msg, 4, 0),
    size: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest;
  return proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMonthlytraveldistance(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPeriodinyears(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFuelpriceineurperl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMonthlytraveldistance();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPeriodinyears();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFuelpriceineurperl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string monthlyTravelDistance = 1;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.getMonthlytraveldistance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.setMonthlytraveldistance = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 periodInYears = 2;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.getPeriodinyears = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.setPeriodinyears = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string fuelPriceInEurPerL = 3;
 * @return {string}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.getFuelpriceineurperl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.setFuelpriceineurperl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 page = 4;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 size = 5;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest} returns this
 */
proto.com.jpan.autodealer.grpc.CarModelSuggestionRequest.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.jpan.autodealer.grpc.PageCarModelResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    contentList: jspb.Message.toObjectList(msg.getContentList(),
    proto.com.jpan.autodealer.grpc.CarModelVO.toObject, includeInstance),
    page: jspb.Message.getFieldWithDefault(msg, 2, 0),
    size: jspb.Message.getFieldWithDefault(msg, 3, 0),
    totalelements: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.jpan.autodealer.grpc.PageCarModelResponse;
  return proto.com.jpan.autodealer.grpc.PageCarModelResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.jpan.autodealer.grpc.CarModelVO;
      reader.readMessage(value,proto.com.jpan.autodealer.grpc.CarModelVO.deserializeBinaryFromReader);
      msg.addContent(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSize(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotalelements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.jpan.autodealer.grpc.PageCarModelResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.jpan.autodealer.grpc.CarModelVO.serializeBinaryToWriter
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTotalelements();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * repeated CarModelVO content = 1;
 * @return {!Array<!proto.com.jpan.autodealer.grpc.CarModelVO>}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.getContentList = function() {
  return /** @type{!Array<!proto.com.jpan.autodealer.grpc.CarModelVO>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.jpan.autodealer.grpc.CarModelVO, 1));
};


/**
 * @param {!Array<!proto.com.jpan.autodealer.grpc.CarModelVO>} value
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} returns this
*/
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.setContentList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.jpan.autodealer.grpc.CarModelVO=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.jpan.autodealer.grpc.CarModelVO}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.addContent = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.jpan.autodealer.grpc.CarModelVO, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} returns this
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.clearContentList = function() {
  return this.setContentList([]);
};


/**
 * optional int32 page = 2;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} returns this
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 size = 3;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} returns this
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 totalElements = 4;
 * @return {number}
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.getTotalelements = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.jpan.autodealer.grpc.PageCarModelResponse} returns this
 */
proto.com.jpan.autodealer.grpc.PageCarModelResponse.prototype.setTotalelements = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.com.jpan.autodealer.grpc.FuelType = {
  DIESEL: 0,
  PETROL: 1,
  ELECTRIC: 2,
  HYDROGEN: 3,
  HYBRID_DIESEL: 4,
  HYBRID_PETROL: 5,
  LPG: 6,
  CNG: 7,
  ETHANOL: 8,
  OTHER: 9
};

goog.object.extend(exports, proto.com.jpan.autodealer.grpc);
